# Travis configuration
language: python

python:
    - "3.6"
    - "3.7"
    - "pypy3"

install:
    - pip install pip --upgrade
    - pip install -r requirements.txt
    - pip install coveralls
    - python -V
    - pip -V
    
script:
    - flake8 --max-line-length=100 engine tests
    - pylint --rcfile=pylint.rcfile engine tests
    - bandit -r engine tests
    - radon cc --show-complexity --min B engine
    - pytest --doctest-modules --cov=engine --cov-branch --cov-fail-under=100 --cov-report=xml --cov-report=term --cov-report=html

after_success:
    - coveralls

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
